# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TeamDivider < Formula
  desc "Command line tool for randomly dividing people into teams"
  homepage "https://github.com/Aldebaranoro/team-divider"
  version "1.2.0"
  license "MIT"

  on_macos do
    url "https://github.com/Aldebaranoro/team-divider/releases/download/v1.2.0/team-divider_1.2.0_macOS_amd64.tar.gz"
    sha256 "6b75758ee178182aa24c6c37d80165e7e596a924279e44a60a9a28a30c0de260"

    def install
      bin.install "bin/team-divider"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the TeamDivider
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Aldebaranoro/team-divider/releases/download/v1.2.0/team-divider_1.2.0_linux_amd64.tar.gz"
      sha256 "a25bce93e5565e191bfb0b0441a39150df567565b665349e7a48be57e4abb520"

      def install
        bin.install "bin/team-divider"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Aldebaranoro/team-divider/releases/download/v1.2.0/team-divider_1.2.0_linux_arm64.tar.gz"
      sha256 "0f9525997f3abdb128c2f1b2dbf73bb3be4f1104dc6e95b6b740e6529f8931b2"

      def install
        bin.install "bin/team-divider"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Aldebaranoro/team-divider/releases/download/v1.2.0/team-divider_1.2.0_linux_armv6.tar.gz"
      sha256 "0c6e96d53502a94adcbf53d6c0f914c444224bbafc9b06a7aae4a013749134ae"

      def install
        bin.install "bin/team-divider"
      end
    end
  end
end
