# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TeamDivider < Formula
  desc "Command line tool for randomly dividing people into teams"
  homepage "https://github.com/Aldebaranoro/team-divider"
  version "1.2.0"
  license "MIT"

  on_macos do
    url "https://github.com/Aldebaranoro/team-divider/releases/download/v1.2.0/team-divider_1.2.0_macOS_amd64.tar.gz"
    sha256 "91e67296136ab51c1346bb4c1851ee4e06b428a48c6554f83efe4f04010cd04e"

    def install
      bin.install "bin/team-divider"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the TeamDivider
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Aldebaranoro/team-divider/releases/download/v1.2.0/team-divider_1.2.0_linux_armv6.tar.gz"
      sha256 "0184a24258707b546b806eddbcd631f949b8542911b8af3d716ff5de809b18b6"

      def install
        bin.install "bin/team-divider"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Aldebaranoro/team-divider/releases/download/v1.2.0/team-divider_1.2.0_linux_arm64.tar.gz"
      sha256 "096740564453dab38a50830cc871a3b2b7df1bbb978533c938643dd5a9041d4f"

      def install
        bin.install "bin/team-divider"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Aldebaranoro/team-divider/releases/download/v1.2.0/team-divider_1.2.0_linux_amd64.tar.gz"
      sha256 "bb750cd2e6736977a676ce405bd225011846a26ec68da4259c5eae05d1d666dd"

      def install
        bin.install "bin/team-divider"
      end
    end
  end
end
