# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TeamDivider < Formula
  desc "Command line tool for randomly dividing people into teams"
  homepage "https://github.com/Aldebaranoro/team-divider"
  version "1.1.5"
  license "MIT"

  on_macos do
    url "https://github.com/Aldebaranoro/team-divider/releases/download/v1.1.5/team-divider_1.1.5_macOS_amd64.tar.gz"
    sha256 "0160fb9dff6980c9764c8746c2201b802a073a37a6d9f7e6781f1944d2da2a08"

    def install
      bin.install "bin/team-divider"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the TeamDivider
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Aldebaranoro/team-divider/releases/download/v1.1.5/team-divider_1.1.5_linux_amd64.tar.gz"
      sha256 "d72daca7e8401cc47ffa499b0bada4474ac104181f590d643554e4b0d5813df9"

      def install
        bin.install "bin/team-divider"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Aldebaranoro/team-divider/releases/download/v1.1.5/team-divider_1.1.5_linux_arm64.tar.gz"
      sha256 "d520122ae52751be570a1948847a3bd6966cbdcf9e38c3718c74ff10a40d2e87"

      def install
        bin.install "bin/team-divider"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Aldebaranoro/team-divider/releases/download/v1.1.5/team-divider_1.1.5_linux_armv6.tar.gz"
      sha256 "cd5a663bad71b8744be1ecbc43aee2e3939da1c8080471ece5e54382311c7472"

      def install
        bin.install "bin/team-divider"
      end
    end
  end
end
